### 设置服务端口和Tomcat编码格式
server:
  port: 26120
  tomcat:
    uri-encoding: UTF-8

### 设置服务名称
spring:
  application:
    name: botong-notice
  sleuth:
    sampler:
      percentage: 1
  rabbitmq:
      host: ${rabbitmq.server}
      port: ${rabbitmq.port}
      username: ${rabbitmq.username}
      password: ${rabbitmq.password}
  datasource:
    url: ${spring.datasource.mysql.url}
    username: ${spring.datasource.mysql.username}
    password: ${spring.datasource.mysql.password}
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    continue-on-error: true
  ##Redis配置
  # Redis数据库索引（默认为0）
  redis:
    database: ${redis.dbindex}
  # Redis服务器地址
    host: ${redis.host}
  # Redis服务器连接端口
    port: ${redis.port}
  # Redis服务器连接密码（默认为空）
    password: ${redis.password}
    # 连接超时时间（毫秒）
    timeout: 0
  # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
  # 连接池中的最大空闲连接
      max-idle: 8
  # 连接池中的最小空闲连接
      min-idle: 0
  ##Redis配置-只读库
  redis-readonly:
    database: ${redis-readonly.dbindex}
    host: ${redis-readonly.host}
    port: ${redis-readonly.port}
    password: ${redis-readonly.password}
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  ##Redis配置-公告
  redis-notice:
    database: ${redis-notice.dbindex}
    host: ${redis-notice.host}
    port: ${redis-notice.port}
    password: ${redis-notice.password}
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0

##配置注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.server}:${eureka.port}/eureka/
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    preferIpAddress: true

##配置mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.yunjing.notice.entity
  global-config:
    meta-object-handler: com.common.mybatis.config.FiledAnnotationMetaObjectHandler
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#Notice-AppId
notice:
     appId: e30af71736f04aacaadc9320d58903e6
#     appId: be61789d315b11e89a1c0242ac110004

##过滤返回null或空字段
#spring:
#  jackson:
#    default-property-inclusion: non_empty

okhttp:
  botong:
    zuul: ${okhttp.botong.zuul}

# 写入文件日志
logging:
  file: ${user.dir}/logs/${spring.application.name}.log

#H5分享地址
h5Address: ${H5Address-notice}
