### 设置服务端口和Tomcat编码格式
server:
  port: 26130
  tomcat:
    uri-encoding: UTF-8

### 注册中心eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.server}:${eureka.port}/eureka/

### 设置服务名称
spring:
  application:
    name: botong-info
  sleuth:
    sampler:
      percentage: 1
  rabbitmq:
      host: ${rabbitmq.server}
      port: ${rabbitmq.port}
      username: ${rabbitmq.username}
      password: ${rabbitmq.password}
  datasource:
    url: ${spring.datasource.mysql.url}
    username: ${spring.datasource.mysql.username}
    password: ${spring.datasource.mysql.password}
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    continue-on-error: true

##配置mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.yunjing.info.model
  global-config:
    meta-object-handler: com.common.mybatis.config.FiledAnnotationMetaObjectHandler
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

# 写入文件日志
logging:
  file: ${user.dir}/logs/${spring.application.name}.log